# Generated by Django 5.0.4 on 2024-06-29 13:48

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLIER = 120

    smartphone_model = apps.get_model('main_app', 'Smartphone')
    for phone in smartphone_model.objects.all():
        phone.price = 120 * len(phone.brand)
        phone.save()


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    for phone in smartphone_model.objects.all():
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'
        phone.save()


def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_price_and_category(apps, schema_editor):
    model = apps.get_model('main_app', 'Smartphone')

    for phone in model.objects.all():
        phone.price = model._meta.get_field('price').default
        phone.category = model._meta.get_field('category').default
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_price_and_category)
    ]
